<a href="https://colab.research.google.com/github/HectorCedilloCharles1/MineriaDeDatos/blob/main/Ej_Limpieza_Equipo5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica 1-Limpieza de datos**

---


#Equipo: 5
#Grupo: 001 Frecuencia: Lunes 7-10pm
#Integrantes:
* 1844452 - Castillo Rodríguez, Leonardo Daniel
* 1851642 - Cedillo Charles, Hector
* 1877422 - Martinez Ortuño, Gustavo Juan
* 1851701 - Navarrete Rosales, Jose Eduardo
* 1869864 - Morales Salazar, César Alejandro

# **1) Google Play Store:**
## a) Google Play Store Apps
## b) https://www.kaggle.com/lava18/google-play-store-apps

#**2) Limpieza de datos:**

# Tarea:  
Dada una base de datos en grupo, realizar las diferentes técnicas de pre procesamiento de datos. Pueden ser las mencionadas en esta práctica, o pueden agregar nuevas. Los temas que tienen que tocar de manera obligatoria:


 * **Importar librerias y base de datos**

In [ ]:
import os
import pandas as pd
import numpy as np

*La base de datos seleccionada es la siguiente:*

In [ ]:
#Leer el archivo
base=pd.read_table('/content/Bases/googleplaystore.csv', sep=',')

* **Visualizar los datos**

In [ ]:
#Visualizamos la base
base

                                                     App  ...         Android Ver
0         Photo Editor & Candy Camera & Grid & ScrapBook  ...        4.0.3 and up
1                                    Coloring book moana  ...        4.0.3 and up
2      U Launcher Lite – FREE Live Cool Themes, Hide ...  ...        4.0.3 and up
3                                  Sketch - Draw & Paint  ...          4.2 and up
4                  Pixel Draw - Number Art Coloring Book  ...          4.4 and up
...                                                  ...  ...                 ...
10836                                   Sya9a Maroc - FR  ...          4.1 and up
10837                   Fr. Mike Schmitz Audio Teachings  ...          4.1 and up
10838                             Parkinson Exercices FR  ...          2.2 and up
10839                      The SCP Foundation DB fr nn5n  ...  Varies with device
10840      iHoroscope - 2018 Daily Horoscope & Astrology  ...  Varies with device

[10841 rows x 13 columns]

In [ ]:
#Otra forma de hacerlo es:
base.head(10)

                                                 App  ...   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...  4.0.3 and up
1                                Coloring book moana  ...  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...  4.0.3 and up
3                              Sketch - Draw & Paint  ...    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ...    4.4 and up
5                         Paper flowers instructions  ...    2.3 and up
6            Smoke Effect Photo Maker - Smoke Editor  ...  4.0.3 and up
7                                   Infinite Painter  ...    4.2 and up
8                               Garden Coloring Book  ...    3.0 and up
9                      Kids Paint Free - Drawing Fun  ...  4.0.3 and up

[10 rows x 13 columns]

* **Descripcion básica de columnas (tipo, elementos, celdas vacias, etc.)**

In [ ]:
print("El número de  filas y columnas es: ",base.shape) 
#Una vez sabido esto, veremos mas a detalle la información que almacenan.
#Con este código vemos las columnas que tiene,  y añade el tipo de dato de la misma
base.dtypes

El número de  filas y columnas es:  (10841, 13)

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

Eliminaremos las columnas de Last Updated, Current Ver y Android Ver, por no ser de utilidad para nuestro análisis, y también removeremos la columna category, puesto que usaremos la de género en este estudio.

In [ ]:
del(base['Last Updated'])
del(base['Current Ver'])
del(base['Android Ver'])
del(base['Category'])

In [ ]:
#Comprobamos que se eliminaron las columnas
base.head(10)

                                                 App  ...                     Genres
0     Photo Editor & Candy Camera & Grid & ScrapBook  ...               Art & Design
1                                Coloring book moana  ...  Art & Design;Pretend Play
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ...               Art & Design
3                              Sketch - Draw & Paint  ...               Art & Design
4              Pixel Draw - Number Art Coloring Book  ...    Art & Design;Creativity
5                         Paper flowers instructions  ...               Art & Design
6            Smoke Effect Photo Maker - Smoke Editor  ...               Art & Design
7                                   Infinite Painter  ...               Art & Design
8                               Garden Coloring Book  ...               Art & Design
9                      Kids Paint Free - Drawing Fun  ...    Art & Design;Creativity

[10 rows x 9 columns]

In [ ]:
#Comprobemos si hay datos nulos, y si sí, en dónde y cuantos
base.isnull().sum()

App                  0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
dtype: int64

* **El objetivo es una clasificación con los datos, asi que hay que acomodar los datos de manera que se nos facilite esta tarea.**

In [ ]:
base=base.reindex(columns=['App','Genres','Installs','Rating','Price','Size',])
base

                                                     App  ...                Size
0         Photo Editor & Candy Camera & Grid & ScrapBook  ...                 19M
1                                    Coloring book moana  ...                 14M
2      U Launcher Lite – FREE Live Cool Themes, Hide ...  ...                8.7M
3                                  Sketch - Draw & Paint  ...                 25M
4                  Pixel Draw - Number Art Coloring Book  ...                2.8M
...                                                  ...  ...                 ...
10836                                   Sya9a Maroc - FR  ...                 53M
10837                   Fr. Mike Schmitz Audio Teachings  ...                3.6M
10838                             Parkinson Exercices FR  ...                9.5M
10839                      The SCP Foundation DB fr nn5n  ...  Varies with device
10840      iHoroscope - 2018 Daily Horoscope & Astrology  ...                 19M

[10841 rows x 6 columns]

* **Cambiar nombres de columnas.**

In [ ]:
#Cambiamos los nombres al español
base=base.rename(columns={'App':'Aplicacion','Genres':'Generos','Installs':'Instalaciones','Price':'Precio','Size':'Tamano'})
base

                                              Aplicacion  ...              Tamano
0         Photo Editor & Candy Camera & Grid & ScrapBook  ...                 19M
1                                    Coloring book moana  ...                 14M
2      U Launcher Lite – FREE Live Cool Themes, Hide ...  ...                8.7M
3                                  Sketch - Draw & Paint  ...                 25M
4                  Pixel Draw - Number Art Coloring Book  ...                2.8M
...                                                  ...  ...                 ...
10836                                   Sya9a Maroc - FR  ...                 53M
10837                   Fr. Mike Schmitz Audio Teachings  ...                3.6M
10838                             Parkinson Exercices FR  ...                9.5M
10839                      The SCP Foundation DB fr nn5n  ...  Varies with device
10840      iHoroscope - 2018 Daily Horoscope & Astrology  ...                 19M

[10841 rows x 6 columns]

* **Guardar otros archivos con agrupaciones.**

In [ ]:
base.to_csv("Base Google PlayStore Modificada.csv")

* **Responder las preguntas de interes.**

* **¿Para que me puede servir estas agrupaciones para la práctica siguiente?**
Este tipo de agrupaciones pudieran llegar a ser de gran utilidad ya que al trabajar con bases de datos muy grandes es recomendable agrupar los datos para poder tener una mejor vision y analisis de los mismos, esto gracias al uso de las clases.

* **Importancia del analisis previo de los datos antes de iniciar las modificaciones.**
Esto es de suma importancia ya que para empezar a trabajar primero debemos saber con que datos estamos trabajando y como los debemos de tratar para  que despues de realizar su respectivo tratamiento y manipulacion poder facilitar su analisis y lograr de una manera mas sencilla el objetivo del trabajo

## Tareas extras: (Puntos extras)

* **Investigar los siguientes comandos: ?df.dropna() ?df.astype**

En cuanto al comando **df.dropna** lo podemos llamar como DataFrame.dropna, este comando nos ayuda a eliminar los datos nulos que tenemos en una base de datos. Este comando tiene la siguiente sintaxis con sus respectivos parámetros df.dropna(axis,how,thresh,subset,inplace). Estos parámetros pueden contener los siguientes valores


*   **Axis:** Puede tomar el valor de 0(o index) y 1(o columns), por default toma el valor de 0. El valor que le damos a la función en este parámetro le indica a la función que eliminar cuando encuentre un valor nulo, si le damos un 0 la función eliminirá la fila donde se encuentre el valor nulo, por el contrario, si es 1 la función eliminará la columna donde este el valor nulo    
*   **How:** Puede tomar el valor de "any" o "all". Este parámetro es el criterio de eliminación de una fila o columa, si decidimos poner "any" como valor de este parámetro el comando eliminirá la fila o columna que contenga al menos un valor nulo, en cambio, si el valor del parámetro "how" es "all" el comando solo eliminará la fila o columna cuando este llena de datos nulos


*   **Thresh:** Este parámetro debe ser un valor entero y es opcional. Se le podriá ver como un seguro, el número entero que pondremos aquí es el minimo de datos NO nulos que debe contener una fila o columna para salvarse de ser eliminada 
*   **Subset:** Es un array opcional. Este parámetro contiene el nombre de unas filas o columnas que queremeos que sean revisadas por el comando. Por ejemplo, si el valor de axis es 1 aqui pondremos el nombre de las filas que queremos que tambien sean consideradas a revisar por el comando

*   **Inplace:** Valor boleano que por default es False. Si el valor de este parámetro es True devuelve un valor nulo al realizar el comando  

Fuente: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

Por su parte la función **df.astype()** cambia el tipo de datos de los objetos a uno en especifico, nos devuelve el dataframe con los tipos de datos fundidos. Su sintaxis es df.astype(dtype,copy,errors,kwargs). Estos parámetros pueden tener los siguientes valores



*   **dtype:** Es el tipo de dato que le queremos asignar a nuestro objeto

*   **Copy:** Valor boleano que por default es True. Cuando es True nos devuelve una copia del objeto modificado. Hay que ser cuidadoso al poner un False en este parámetro ya que los valores cambiados pueden propagarse a otros objetos

*   **Errors:** Puede tener el valor de raise o ignore. Este parámetro controla el lanzamiento de excepciones sobre datos no válidos para el tipo de dato proporcionado. Con raise ignora las excepciones, y con ignore las elimina, si ocurre un error al momento de correr la función regresa el objeto original
*   **kwargs:** Palabra clave que sirve de argumento para pasar al constructor

Fuente: https://www.geeksforgeeks.org/python-pandas-dataframe-astype/

* **Realizar una tarea de preprocesamiento no mencionada en esta práctica.**

Primero agrupamos los datos por **Category**. Después, utilizando el comando "*Aggregate(.agg)*", agregamos el máximo y mínimo de la columna Rating de cada grupo.

In [ ]:
basegroup_Category=base.groupby('Category')

basegroup_Category.agg({'Rating': [('Rating_Max', np.max), ('Rating_Min', np.min)]})

                        Rating
                    Rating_Max Rating_Min
Category
1.9                       19.0       19.0
ART_AND_DESIGN             5.0        3.2
AUTO_AND_VEHICLES          4.9        2.1
BEAUTY                     4.9        3.1
BOOKS_AND_REFERENCE        5.0        2.7
BUSINESS                   5.0        1.0
COMICS                     5.0        2.8
COMMUNICATION              5.0        1.0
DATING                     5.0        1.0
EDUCATION                  4.9        3.5
ENTERTAINMENT              4.7        3.0
EVENTS                     5.0        2.9
FAMILY                     5.0        1.0
FINANCE                    5.0        1.0
FOOD_AND_DRINK             5.0        1.7
GAME                       5.0        1.0
HEALTH_AND_FITNESS         5.0        1.4
HOUSE_AND_HOME             4.8        2.8
LIBRARIES_AND_DEMO         5.0        3.1
LIFESTYLE                  5.0        1.5
MAPS_AND_NAVIGATION        4.9        1.9
MEDICAL                    5.0        1.0
NEWS_AND_MAGAZINES         5.0        1.7
PARENTING                  5.0        2.0
PERSONALIZATION            5.0        2.5
PHOTOGRAPHY                5.0        2.0
PRODUCTIVITY               5.0        1.0
SHOPPING                   5.0        1.6
SOCIAL                     5.0        1.9
SPORTS                     5.0        1.5
TOOLS                      5.0        1.0
TRAVEL_AND_LOCAL           5.0        2.2
VIDEO_PLAYERS              4.9        1.8
WEATHER                    4.8        3.3

In [ ]:
import pandas as pd
data = {'A':[1,4,7],'B':[2,5,8],'C':[3,6,9]}
df = pd.DataFrame(data)
df.agg(['sum','mean'])

         A     B     C
sum   12.0  15.0  18.0
mean   4.0   5.0   6.0